// src/utils/exportPdf.js

export const exportProjectToPDF = (project) => {
  if (!project) return;

  const printWindow = window.open('', '_blank');
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${project.projectName || 'Project Export'}</title>
      <meta charset="UTF-8">
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: 'Segoe UI', Arial, sans-serif;
          padding: 40px;
          max-width: 900px;
          margin: 0 auto;
          line-height: 1.6;
          color: #1f2937;
        }
        h1 {
          color: #7c3aed;
          border-bottom: 3px solid #7c3aed;
          padding-bottom: 10px;
          margin-bottom: 20px;
        }
        h2 {
          color: #6b21a5;
          margin-top: 25px;
          margin-bottom: 10px;
          font-size: 1.3em;
        }
        .badge {
          display: inline-block;
          background: #f3e8ff;
          color: #7c3aed;
          padding: 4px 12px;
          border-radius: 20px;
          font-size: 12px;
          margin-right: 8px;
          margin-bottom: 8px;
        }
        .meta {
          background: #f9fafb;
          padding: 15px;
          border-radius: 8px;
          margin: 15px 0;
        }
        .section {
          margin-bottom: 25px;
        }
        ul, ol {
          padding-left: 25px;
          margin-top: 8px;
        }
        li {
          margin: 5px 0;
        }
        hr {
          margin: 20px 0;
          border-color: #e5e7eb;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          color: #9ca3af;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <h1>${project.projectName || 'Project Idea'}</h1>
      
      <div class="meta">
        <span class="badge">📚 ${project.techStackSelected || project.techStack?.[0] || 'N/A'}</span>
        <span class="badge">🎯 ${project.difficulty || 'N/A'}</span>
        <span class="badge">⏱️ ${project.timeline || 'N/A'}</span>
        <span class="badge">💻 ${project.projectType || 'Full Stack'}</span>
      </div>
      
      <div class="section">
        <h2>📖 Description</h2>
        <p>${project.description || 'No description provided.'}</p>
      </div>
      
      <div class="section">
        <h2>✨ Key Features</h2>
        <ul>
          ${project.keyFeatures?.map(f => `<li>${f}</li>`).join('') || '<li>No features listed</li>'}
        </ul>
      </div>
      
      <div class="section">
        <h2>🛠️ Tech Stack</h2>
        <ul>
          ${project.techStack?.map(t => `<li>${t}</li>`).join('') || '<li>No tech stack specified</li>'}
        </ul>
      </div>
      
      ${project.databaseSchema ? `
      <div class="section">
        <h2>🗄️ Database Schema</h2>
        <p>${project.databaseSchema}</p>
      </div>
      ` : ''}
      
      ${project.apiEndpoints?.length ? `
      <div class="section">
        <h2>🔌 API Endpoints</h2>
        <ul>
          ${project.apiEndpoints.map(e => `<li><code>${e}</code></li>`).join('')}
        </ul>
      </div>
      ` : ''}
      
      <div class="section">
        <h2>📅 Implementation Roadmap</h2>
        <ol>
          ${project.implementationRoadmap?.map(r => `<li>${r}</li>`).join('') || '<li>No roadmap available</li>'}
        </ol>
      </div>
      
      <div class="section">
        <h2>🚀 Deployment Guidance</h2>
        <p>${project.deploymentGuidance || 'Not specified'}</p>
      </div>
      
      ${project.futureEnhancements?.length ? `
      <div class="section">
        <h2>🔮 Future Enhancements</h2>
        <ul>
          ${project.futureEnhancements.map(e => `<li>${e}</li>`).join('')}
        </ul>
      </div>
      ` : ''}
      
      <hr />
      <div class="footer">
        Generated by AI Project Generator
      </div>
    </body>
    </html>
  `);
  
  printWindow.document.close();
  printWindow.print();
};